import next from 'eslint-config-next/core-web-vitals';
import sonarjs from 'eslint-plugin-sonarjs';
import tseslint from 'typescript-eslint';

/**
 * Flat config, using the native presets both plugins now ship.
 *
 * `eslint-config-next/core-web-vitals` already bundles the base `next` and
 * `next/typescript` configs, so it is the only Next preset needed — and going
 * direct means the `@eslint/eslintrc` compatibility bridge can be dropped.
 */
const eslintConfig = [
  {
    ignores: ['.next/**', 'out/**', 'build/**', 'coverage/**', 'next-env.d.ts', '*.tsbuildinfo'],
  },

  ...next,

  /**
   * `eslint-config-next` still routes plain JS through its own Babel parser,
   * whose scope manager predates the `addGlobals` API ESLint 10 calls on every
   * file — so linting any `.mjs` throws before a single rule runs. The
   * TypeScript parser handles plain JS perfectly well, and it is already loaded
   * for everything under `src`. Remove this once Next ships an ESLint 10 parser.
   */
  {
    files: ['**/*.{js,cjs,mjs,jsx}'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: { sourceType: 'module', ecmaFeatures: { jsx: true } },
    },
  },

  /**
   * SonarQube's own rule set for JavaScript and TypeScript, run through ESLint.
   * Bug-detection and maintainability rules that `eslint-config-next` does not
   * cover — surfaced in the editor, with no server or scan to configure.
   */
  sonarjs.configs.recommended,

  {
    rules: {
      // 15 is generous for presentational components; 12 still leaves room for
      // a component with a couple of conditional branches.
      'sonarjs/cognitive-complexity': ['warn', 12],

      // Class name strings repeat across sibling elements and brand hexes repeat
      // across the data files. Neither is duplication worth extracting, and
      // flagging them buries the findings that matter.
      'sonarjs/no-duplicate-string': 'off',

      // Every use here is a JSON-LD blob or the theme bootstrap — generated by
      // this codebase, never derived from user input.
      'sonarjs/no-dangerously-set-inner-html': 'off',

      eqeqeq: ['error', 'smart'],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'prefer-const': 'error',
      'object-shorthand': ['error', 'always'],
    },
  },

  /**
   * Typed rules only where the TypeScript plugin is registered — the `next`
   * preset scopes it to `.ts`/`.tsx`, and referencing it outside that scope is
   * a hard config error rather than a no-op.
   */
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      // Unused code fails rather than warns: it is how the dead files this
      // project started with went unnoticed for so long.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
];

export default eslintConfig;
